Add information about Rider support
AvaloniaUI/avaloniaui.net pull request #224
Opened 2020-12-29 10:59 UTC by grokys

**What kind of change does this PR introduce?**

Rider now ships with inbuilt Avalonia support. Generalize stuff that was previously VS-specific to also include Rider.

2021-01-02 16:46 UTC, rstm-sf commented on src/AvaloniaUI.Net/wwwroot/docs/quickstart/ide-support.md
> +The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has inbuilt support for Avalonia XAML starting in 2020.2 including first-class support for Avalonia-specific XAML features and custom code
Isn't it from the 2020.3 version?

2021-01-08 14:19 UTC, khalidabuhakmeh requested changes
I've added evergreen links in place of directing to the what's new page directly. This will make sure these links don't get broken as we release new versions of Rider.

2021-01-08 14:19 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/index.md
> +The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has inbuilt support for Avalonia XAML [starting in 2020.2](https://www.jetbrains.com/rider/whatsnew/#avalonia-support) including first-clas
```suggestion
The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has built-in support for Avalonia XAML [starting in 2020.3](https://www.jetbrains.com/rider/whatsnew/2020-3/#version-2020-3-avalonia-support) including first-class support for Avalonia-specific XAML features and custom code inspections. We also have a [Visual Studio extension](/docs/quickstart/ide-support).
```

2021-01-08 14:19 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/index.md
> +The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has inbuilt support for Avalonia XAML [starting in 2020.2](https://www.jetbrains.com/rider/whatsnew/#avalonia-support) including first-clas
I added an _evergreen_ link to make sure that the link doesn't get broken.

2021-01-08 14:19 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/quickstart/create-new-project.md
> +The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has inbuilt support for Avalonia XAML [starting in 2020.2](https://www.jetbrains.com/rider/whatsnew/#avalonia-support) including first-clas
```suggestion
The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has built-in support for Avalonia XAML [starting in 2020.3](https://www.jetbrains.com/rider/whatsnew/2020-3/#version-2020-3-avalonia-support) including first-class support for Avalonia-specific XAML features and custom code inspections.
```

2021-01-08 14:19 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/quickstart/ide-support.md
> +The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has inbuilt support for Avalonia XAML starting in 2020.2 including first-class support for Avalonia-specific XAML features and custom code
```suggestion
The [JetBrains Rider](https://www.jetbrains.com/rider/) IDE has built-in support for Avalonia XAML [starting in 2020.3](https://www.jetbrains.com/rider/whatsnew/2020-3/#version-2020-3-avalonia-support) including first-class support for Avalonia-specific XAML features and custom code inspections.
```

2021-01-08 14:19 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/quickstart/ide-support.md
> +See the [blog post](https://www.jetbrains.com/rider/whatsnew/#avalonia-support) for more information,.
```suggestion
See the [JetBrains Rider 2020.3 release announcement](https://www.jetbrains.com/rider/whatsnew/2020-3/#version-2020-3-avalonia-support) for more information,.
```

2021-01-08 14:36 UTC, khalidabuhakmeh commented on src/AvaloniaUI.Net/wwwroot/docs/quickstart/ide-support.md
>  The [Avalonia for Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio) includes a XAML designer which can be used to show a live preview
```suggestion
### Avalonia Visual Studio Extension

The [Avalonia for Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio) includes a XAML designer which can be used to show a live preview of the XAML as you're writing it. With the Avalonia for Visual Studio extension installed, double click on an Avalonia XAML file to open it.

### ReSharper for Visual Studio

For Visual Studio and ReSharper users, [ReSharper 2020.3 introduces](https://www.jetbrains.com/resharper/whatsnew/2020-3/#version-2020-3-avalonia-support) built-in code analysis, code completion, navigation, and find usages.
```

2021-01-11 17:45 UTC, grokys commented
Thanks @khalidabuhakmeh, suggestions committed!

2021-01-15 15:05 UTC, merged